name: Release packages

on:
  release:
    types: [published]

jobs:
  releasePackages:
    name: Release packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm i

      - name: Build @astral/ui
        run: npm run build --workspace=@astral/ui
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
      - name: Publish @astral/ui
        run: npm publish ./packages/ui/lib
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Build @astral/icons
        run: npm run build --workspace=@astral/icons
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
      - name: Publish @astral/icons
        run: npm publish ./packages/icons/lib
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Build @astral/fonts
        run: npm run build --workspace=@astral/fonts
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
      - name: Publish @astral/fonts
        run: npm publish ./packages/fonts/lib
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Build @astral/illustrations
        run: npm run build --workspace=@astral/illustrations
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
      - name: Publish @astral/illustrations
        run: npm publish ./packages/illustrations/lib
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

#      - name: Build @astral/form
#        run: npm run build --workspace=@astral/form
#        env:
#          RELEASE_TAG: ${{ github.event.release.tag_name }}
#      - name: Publish @astral/form
#        run: npm publish ./packages/form/lib
#        env:
#          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_SECRET }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        id: cpr
        with:
          branch: main-release-${{ github.event.release.tag_name }}
          delete-branch: true
          base: main
          add-paths: packages/**/*.json
          commit-message: 'chore: –û–±–Ω–æ–≤–ª–µ–Ω—ã –≤–µ—Ä—Å–∏–∏ –ø–∞–∫–µ—Ç–æ–≤ –¥–æ ${{ github.event.release.tag_name }}'
          title: 'chore: –û–±–Ω–æ–≤–ª–µ–Ω—ã –≤–µ—Ä—Å–∏–∏ –ø–∞–∫–µ—Ç–æ–≤ –¥–æ ${{ github.event.release.tag_name }}'

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}

      - name: Auto approve from Code Owner
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.OWNER_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}

      - name: Auto approve from Code Owner 2
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.SECOND_OWNER_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}

  notify:
    name: notify
    needs: releasePackages
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on release
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_RELEASE_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            üöÄ <b>–ë—ã–ª–∏ –æ–ø—É–±–ª–∏–∫–æ–≤–∞–Ω—ã –Ω–æ–≤—ã–µ –≤–µ—Ä—Å–∏–∏ –ø–∞–∫–µ—Ç–æ–≤ ui-kit !</b>

            –û–ø—É–±–ª–∏–∫–æ–≤–∞–Ω–Ω—ã–µ –ø–∞–∫–µ—Ç—ã:

            üì¶  @astral/ui: ${{ github.event.release.tag_name }}
            üì¶  @astral/fonts: ${{ github.event.release.tag_name }}
            üì¶  @astral/icons: ${{ github.event.release.tag_name }}
            üì¶  @astral/illustrations: ${{ github.event.release.tag_name }}
            üì¶  @astral/form: ${{ github.event.release.tag_name }}

            ‚ö°Ô∏è <a href="${{ github.event.release.html_url }}">Changelog</a>

            ‚ö°Ô∏è <a href="https://main--61baeff6f06230003a88ef8a.chromatic.com">–°—Ç–µ–Ω–¥ storybook –¥–ª—è ui-kit.</a>

            ‚ö°Ô∏è –ù–æ–≤—ã–π ui-kit - —ç—Ç–æ –Ω–∞—à open source, —Ä–µ–ø–æ–∑–∏—Ç–æ—Ä–∏–π –º–æ–∂–µ—Ç–µ –Ω–∞–π—Ç–∏ <a href="${{ github.event.repository.html_url }}">–∑–¥–µ—Å—å</a>. –õ—é–±–æ–π –∂–µ–ª–∞—é—â–∏–π –º–æ–∂–µ—Ç –≤–Ω–µ—Å—Ç–∏ —Å–≤–æ–π –≤–∫–ª–∞–¥ –≤ —Ä–∞–∑–≤–∏—Ç–∏–µ –ø—Ä–æ–µ–∫—Ç–∞.
