name: CI for package @astral/ui

on:
  pull_request:
    branches:
      - main

jobs:
  prepare-yarn:
    name: Prepare yarn
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - name: Validate cache
        run: yarn --immutable

  lint:
    name: Running linter
    runs-on: ubuntu-latest
    needs: prepare-yarn
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - name: Install dependencies
        run: yarn --immutable
      - name: Run eslint
        run: yarn workspace @astral/ui lint

  test:
    name: Running tests
    runs-on: ubuntu-latest
    needs: prepare-yarn
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - name: Install dependencies
        run: yarn --immutable
      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v1
      - name: Run jest
        env:
          CI: true
        run: yarn workspace @astral/ui test --ci --maxWorkers=${{ steps.cpu-cores.outputs.count }}

  build:
    name: Running build
    runs-on: ubuntu-latest
    needs: prepare-yarn
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - name: Install dependencies
        run: yarn --immutable
      - name: Run build
        env:
          CI: true
        run: yarn workspace @astral/ui build

  notify:
    name: telegram message
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on PR
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created Pull Request
            Title: ${{ github.event.pull_request.title }}
            See changes: ${{ github.event.pull_request.html_url }}
            
            Reviewers: ${{ github.event.pull_request.requested_reviewers[0].login }}, ${{ github.event.pull_request.requested_reviewers[1].login }}
